spring.application.name=watchtogether-server
server.port=${PORT:8080}
server.address=0.0.0.0

spring.websocket.allowed-origins=*

server.forward-headers-strategy=native

logging.level.com.watchtogether=DEBUG
logging.level.org.springframework.web.socket=INFO